preset: psr2

enabled:
  - short_array_syntax
  - empty_return
  - join_function
  - multiline_array_trailing_comma
  - namespace_no_leading_whitespace
  - no_blank_lines_after_class_opening
  - operators_spaces
  - phpdoc_indent
  - remove_leading_slash_use
  - remove_lines_between_uses
  - return
  - single_array_no_trailing_comma
  - single_blank_line_before_namespace
  - spaces_before_semicolon
  - spaces_cast
  - standardize_not_equal
  - ternary_spaces
  - unused_use
  - align_double_arrow
  - no_blank_lines_before_namespace
  - ordered_use
  - phpdoc_order
